#!/bin/bash --login

### Define Resources needed:
#PBS -l walltime=36:00:00
#PBS -l nodes=1:ppn=1
#PBS -l mem=20gb
#PBS -l feature=intel14
### Name job
#PBS -N T-256_G-16_A-64_P-1.0
### Email stuff
#PBS -M lalejini@msu.edu
#PBS -m ae
### Setup multiple replicates
#PBS -t 1-10
### Combine and redirect output/error logs
#PBS -j oe

cd ${PBS_O_WORKDIR}

DATA_DIR=${HOME}/Data/evo-foraging-exp/testing/qsub_test/
REP_DIR=${DATA_DIR}/${PBS_JOBNAME}/rep_${PBS_ARRAYID}/
mkdir -p ${REP_DIR}
mkdir -p ${REP_DIR}/output

cp ${PBS_JOBNAME}_U-50000.cfg ${REP_DIR}
cp MABE ${REB_DIR}

cd ${REP_DIR}

./MABE configFileName ./${PBS_JOBNAME}_U-50000.cfg outputDirectory ./output/ randomSeed ${PBS_ARRAYID}  > ${REP_DIR}/log 2>&1

qstat -f ${PBS_JOBID}
